# Site settings
title: Security Blog
description: Interesting shares and findings about security are updated here :) 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yash Bharadwaj
user_description: I am a Security Researcher with deep interest in Windows Internals, Bypassing AV's, Active Directory pentesting. I love to talk about technology and Network Security. A simple guy with revolutionary thoughts and actions.     
user_title: Security Researcher
email: bharadwajyash3@gmail.com
twitter_username: https://twitter.com/flopyash
github_username: https://github.com/bharadwajyas
linkedin_username: bharadwaj-yash
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
